src/Cenfotec/SeguridadBundle/Entity/Usuario.php
<?php

namespace Cenfotec\SeguridadBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * Cenfotec\SeguridadBundle\Entity\Usuario
 *
 * @ORM\Table(name="t_usuario")
 * @ORM\Entity(repositoryClass="\Cenfotec\SeguridadBundle\Repository\UsuarioRepository")
 */
class Usuario implements UserInterface
{
    /**
     * @var integer $id
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;
    
    /**
     * @ORM\Column(name="nombre", type="string", length=50)
     */
    private $nombre;
    
    /**
     * @ORM\Column(name="apellido1", type="string", length=50)
     */
    private $apellido1;
    
    /**
     * @ORM\Column(name="apellido2", type="string", length=50)
     */
    private $apellido2;
    
    /**
     * @ORM\Column(name="nombre_usuario", type="string", length=25, unique=true)
     */
    private $nombreUsuario;
    
     /**
     * @ORM\Column(name="salt", type="string", length=32)
     */
    private $salt;
    
    /**
     * @ORM\Column(name="password", type="string", length=255)
     */
    private $password;
    
    /**
     * @ORM\Column(name="correo", type="string", length=60, unique=true)
     */
    private $correo;
    
    /**
     * @ORM\ManyToMany(targetEntity="Rol", inversedBy="usuarios")
     * @ORM\JoinTable(name="t_usuario_rol",
     *      joinColumns={@ORM\JoinColumn(name="usuario_id", referencedColumnName="id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="rol_id", referencedColumnName="id")}
     *      )
     */
    private $roles;
    
    /**
     * Constructor
     */
    public function __construct()
    {
        $this->roles = new \Doctrine\Common\Collections\ArrayCollection();
    }
    
    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Get nombreCompleto
     *
     * @return string 
     */
    public function getNombreCompleto()
    {
        return $this->nombre . ' ' . $this->apellido1 . ' ' . $this->apellido2;
    }
    
    /**
     * Set nombreUsuario
     *
     * @param string $nombreUsuario
     * @return Usuario
     */
    public function setNombreUsuario($nombreUsuario)
    {
        $this->nombreUsuario = $nombreUsuario;
    
        return $this;
    }

    /**
     * Get nombreUsuario
     *
     * @return string 
     */
    public function getNombreUsuario()
    {
        return $this->nombreUsuario;
    }

    /**
     * Get Username
     *
     * @return string 
     */
    public function getUsername() 
    {
        return $this->nombreUsuario;
    }

    /**
     * Set salt
     *
     * @param string $salt
     * @return Usuario
     */
    public function setSalt($salt)
    {
        $this->salt = $salt;
    
        return $this;
    }

    /**
     * Get Username
     *
     * @return string 
     */
    public function getSalt() 
    {
        return $this->salt;
    }
    
    /**
     * Set password
     *
     * @param string $password
     * @return Usuario
     */
    public function setPassword($password)
    {
        $this->password = $password;
    
        return $this;
    }

    /**
     * Get password
     *
     * @return string 
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * Set correo
     *
     * @param string $correo
     * @return Usuario
     */
    public function setCorreo($correo)
    {
        $this->correo = $correo;
    
        return $this;
    }

    /**
     * Get correo
     *
     * @return string 
     */
    public function getCorreo()
    {
        return $this->correo;
    }
    
    /**
     * Array con los permisos del usuario
     *
     * @return array 
     */
    public function getPermisos() 
    {
        $roles           = $this->roles;
        $permisosUsuario = array();
        
        //Recorrer los roles que tiene asignado el usuario.
        foreach ($roles as $objRol) {
            $permisosRol  = $objRol->getPermisos();
            
            //Recorrer los permisos que tiene asignado cada rol
            foreach ($permisosRol as $objPermiso) {
                $permisosUsuario[] = $objPermiso->getNombre();
            }
        }
        
        //Varios Roles pueden tener un mismo permiso asi que hay que remover los duplicados.
        return array_unique($permisosUsuario);
    }
    
    /**
     * Get Roles (Es como obtener los permisos del usuario) 
     * NOTA: Si se cambia a getPermisos pasan muchos problemas
     *
     * @return array 
     */
    public function getRoles() 
    {
        $roles        = $this->roles;
        $rolesUsuario = array();
        
        //Obtener los nombres de los roles del usuario
        foreach ($roles as $objRol) {
            $rolesUsuario[] = $objRol->getNombre();
        }
        
        //Varios Roles pueden tener un mismo permiso asi que hay que remover los duplicados.
        return array_unique($rolesUsuario);
    }
    
    /**
     * Obtiene los roles del usuario
     *
     * @return array 
     */
    public function getRealRoles() 
    {
        return $this->roles;
    }
    
    /**
     * Set Roles
     *
     * @param \Doctrine\Common\Collections\Collection $roles
     */
    public function setRoles(\Doctrine\Common\Collections\ArrayCollection $roles)
    {
        $this->roles = $roles;
        return $this;
    }
    
    /**
     * Add roles
     *
     * @param \Cenfotec\SeguridadBundle\Entity\Rol $roles
     * @return Usuario
     */
    public function addRole(\Cenfotec\SeguridadBundle\Entity\Rol $roles)
    {
        $this->roles[] = $roles;
    
        return $this;
    }

    /**
     * Remove roles
     *
     * @param \Cenfotec\SeguridadBundle\Entity\Rol $roles
     */
    public function removeRole(\Cenfotec\SeguridadBundle\Entity\Rol $roles)
    {
        $this->roles->removeElement($roles);
    }

    /**
     * Set nombre
     *
     * @param string $nombre
     * @return Usuario
     */
    public function setNombre($nombre)
    {
        $this->nombre = $nombre;
    
        return $this;
    }

    /**
     * Get nombre
     *
     * @return string 
     */
    public function getNombre()
    {
        return $this->nombre;
    }

    /**
     * Set apellido1
     *
     * @param string $apellido1
     * @return Usuario
     */
    public function setApellido1($apellido1)
    {
        $this->apellido1 = $apellido1;
    
        return $this;
    }

    /**
     * Get apellido1
     *
     * @return string 
     */
    public function getApellido1()
    {
        return $this->apellido1;
    }

    /**
     * Set apellido2
     *
     * @param string $apellido2
     * @return Usuario
     */
    public function setApellido2($apellido2)
    {
        $this->apellido2 = $apellido2;
    
        return $this;
    }

    /**
     * Get apellido2
     *
     * @return string 
     */
    public function getApellido2()
    {
        return $this->apellido2;
    }
    
    public function eraseCredentials() 
    {
        
    }
}

src/Cenfotec/SeguridadBundle/Controller/UsuarioController.php
<?php

namespace Cenfotec\SeguridadBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Bundle\FrameworkBundle\Templating\Asset\PathPackage;
use Components\EJSTreeGridBundle\Framework\GridOptionsGenerator,
    Components\EJSTreeGridBundle\Framework\GridLayoutGenerator,
    Components\EJSTreeGridBundle\Framework\GridDataTreePagingFormatter;

// these import the "@Route" and "@Template" annotations
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;

/**
* @Route("/usuario")
*/
class UsuarioController extends Controller
{
    /**
     * @Route("/", name="cenfo_usuario_administrar")
     * @Template()
     */
    public function administrarAction()
    {
        $router               = $this->get('router');
        $gridOptionsGenerator = new GridOptionsGenerator('ContainerGridUsuario');
        
        $gridOptionsGenerator
            ->setGridId('GridUsuario')
            ->setOptions(array(
                'Layout_Url' => $router->generate('cenfo_usuario_grid_layout'),
                'Data_Url'   => $router->generate('cenfo_usuario_grid_data'),
                'Upload_Url' => $router->generate('cd_ejstreegrid_upload_default'),
                'Export_Url' => $router->generate('cd_ejstreegrid_export'),
            ));
        
        return array( 
            'gridOptionsGenerator' => $gridOptionsGenerator
        );
    }
    
    /**
     * @Route("/grid-layout", name="cenfo_usuario_grid_layout", defaults={"_format" = "json"})
     * @Template("ComponentsEJSTreeGridBundle::gridLayout.json.twig")
     */
    public function gridLayoutUsuarioAction()
    {
        $r                 = $this->getRequest();
        $layoutGenerator   = new GridLayoutGenerator();
        
        $textColumnDefault = array(
            'CanEdit'   => 0,
            'RelWidth'  => 1,
            'CanFilter' => 1,
            'CanSort'   => 1,
            'Type'      => "Text",
            'Align'     => 'Left',
        );
        
        $columns = array(
            array(
                'CanEdit'   => 1,
                'Width'     => 0,
                'Name'      => "id",
                'Type'      => "Text",
            ),array(
                'Width'     => 0,
                'Name'      => "Name",
                'Type'      => "Text", 
            ),array_merge(array(
                'Name' => "NombreCompleto"
            ), $textColumnDefault),array_merge(array(
                'Name' => "Usuario"
            ), $textColumnDefault),array_merge(array(
                'Name' => "Rol"
            ), $textColumnDefault)
        );
        
        $layoutGenerator->addTopRowFilter(array(
            'id' => "Filter"
        ));
        $layoutGenerator->setVariableColumns($columns);
        
        $layoutGenerator->setPanel(array(
            'Delete' => 0
        ))->setToolbar(array(
            'Cells'         => "Reload,Export,Cnt,Sel",
            'CanFocus'      => '0',

            'CntRelWidth'   => '1',
            'CntType'       => 'Html',
            'CntFormula'    => '"Filas:<b>"+count(7)+"</b> Mostrando:<b>"+count(6)+"</b>"',
            'CntAlign'      => 'Right',
            'CntPrintHPage' => '2',

            'SelType'       => 'Html',
            'SelFormula'    => 'var cnt=count(15);return cnt?"Selección:<b>"+cnt+"</b>":""',
            'SelWidth'      => '-1',
            'SelWrap'       => '0',
            'SelPrintHPage' => '2',
        ));
        
        return array('gridLayoutGenerator' => $layoutGenerator);
    }
    
    /**
     * @Route("/grid-data", name="cenfo_usuario_grid_data", defaults={"_format" = "json"})
     * @Template("ComponentsEJSTreeGridBundle::gridData.json.twig")
     */
    public function gridDataUsuarioAction() 
    { 
        $r             = $this->getRequest();
        $dataFormatter = new GridDataTreePagingFormatter();
        $usuarios      = $this->getDoctrine()->getRepository('CenfotecSeguridadBundle:Usuario')->findBy(array(), array('nombre'=>'asc'));
        
        foreach ($usuarios as $objUsuario) {
            $roles = array();
            
            foreach ($objUsuario->getRealRoles() as $objRol) {
                $roles[] = $objRol->getNombre();
            }
            
            $row = array(
                'id'             => $objUsuario->getId(),
                'Name'           => $objUsuario->getNombreCompleto(),
                'NombreCompleto' => $objUsuario->getNombreCompleto(),
                'Usuario'        => $objUsuario->getNombreUsuario(),
                'Rol'            => implode(', ', $roles)
            );
            $dataFormatter->addRow($row);
        }
        return array('gridDataFormatter' => $dataFormatter);
    }
    
    /**
     * @Route("/form-registrar", name="cenfo_usuario_form_registrar")
     * @Template("CenfotecSeguridadBundle:Usuario:formRegistrar.html.twig")
     */
    public function formRegistrarAction()
    {
        $roles = $this->getDoctrine()->getRepository('CenfotecSeguridadBundle:Rol')->findBy(array(), array('nombre'=>'asc'));
        return array(
            'ptwRoles' => $roles
        );
    }
    
    /**
     * @Route("/form-modificar", name="cenfo_usuario_form_modificar")
     * @Template("CenfotecSeguridadBundle:Usuario:formModificar.html.twig")
     */
    public function formModificarAction()
    {
        $doctrine   = $this->getDoctrine();
        $pidUsuario = $this->getRequest()->query->get('pidUsuario');
        $objUsuario = $doctrine->getRepository('CenfotecSeguridadBundle:Usuario')->find($pidUsuario);
        $roles      = $doctrine->getRepository('CenfotecSeguridadBundle:Rol')->findBy(array(), array('nombre'=>'asc'));
        
        return array(
            'ptwObjUsuario' => $objUsuario,
            'ptwRoles'      => $roles
        );
    }
    
    /**
     * @Route("/registrar", name="cenfo_usuario_registrar")
     */
    public function registrarAction()
    {
        $r               = $this->getRequest();
        $em              = $this->getDoctrine()->getEntityManager();
        $repoRol         = $em->getRepository('CenfotecSeguridadBundle:Rol');
        $uiDataUsuario   = $r->request->get('uiDataNuevoUsuario');
        $factory         = $this->get('security.encoder_factory');
        
        //Crear el nuevo usuario.
        $objNuevoUsuario = new \Cenfotec\SeguridadBundle\Entity\Usuario();
        $encoder         = $factory->getEncoder($objNuevoUsuario);
        $objNuevoUsuario->setSalt(md5(time()));
        $password       = $encoder->encodePassword($uiDataUsuario['Password'], $objNuevoUsuario->getSalt());
        $objNuevoUsuario->setCorreo($uiDataUsuario['Correo']);
        $objNuevoUsuario->setPassword($password);
        $objNuevoUsuario->setNombre($uiDataUsuario['Nombre']);
        $objNuevoUsuario->setApellido1($uiDataUsuario['Apellido1']);
        $objNuevoUsuario->setApellido2($uiDataUsuario['Apellido2']);
        $objNuevoUsuario->setNombreUsuario($uiDataUsuario['NombreUsuario']);
        
        //Agregar los roles que se le asignaron al usuario
        foreach ($uiDataUsuario['Roles'] as $idRol) {
            $objRol = $repoRol->find($idRol);
            $objNuevoUsuario->addRole($objRol);
        }
        
        //Registrarlo a base de datos.
        $em->persist($objNuevoUsuario);
        $em->flush();
        
        //mostrar el mensaje de que se registro correctamente el usuario
        $this->get('session')->setFlash(
            'notice',
            'El usuario ' . $objNuevoUsuario->getNombreUsuario() . ' se ha creado correctamente.'
        );
        
        return $this->redirect($this->generateUrl('cenfo_usuario_administrar'));
    }

    /**
     * @Route("/modificar", name="cenfo_usuario_modificar")
     */
    public function modificarAction()
    {
        $r             = $this->getRequest();
        $em            = $this->getDoctrine()->getEntityManager();
        $repoRol       = $em->getRepository('CenfotecSeguridadBundle:Rol');
        $pidUsuario    = $r->query->get('pidUsuario');
        $uiDataUsuario = $r->request->get('uiDataUsuario');
        $factory       = $this->get('security.encoder_factory');
        
        //Crear el nuevo usuario.
        $objUsuario = $em->getRepository('CenfotecSeguridadBundle:Usuario')->find($pidUsuario);
        $encoder    = $factory->getEncoder($objUsuario);
        
        $objUsuario->setCorreo($uiDataUsuario['Correo']);
        $objUsuario->setNombre($uiDataUsuario['Nombre']);
        $objUsuario->setApellido1($uiDataUsuario['Apellido1']);
        $objUsuario->setApellido2($uiDataUsuario['Apellido2']);
        $objUsuario->setNombreUsuario($uiDataUsuario['NombreUsuario']);
        
        if($uiDataUsuario['Password'] != $objUsuario->getPassword()){
            $objUsuario->setSalt(md5(time()));
            $password = $encoder->encodePassword($uiDataUsuario['Password'], $objUsuario->getSalt());
            $objUsuario->setPassword($password);
        }
        
        //Quitar los roles, para agregar los que el usuario ingreso.
        $objUsuario->setRoles(new \Doctrine\Common\Collections\ArrayCollection());
                
        //Agregar los roles que se le asignaron al usuario
        foreach ($uiDataUsuario['Roles'] as $idRol) {
            $objRol = $repoRol->find($idRol);
            $objUsuario->addRole($objRol);
        }
        
        //Registrarlo a base de datos.
        $em->persist($objUsuario);
        $em->flush();
       
        return new \Symfony\Component\HttpFoundation\Response('done');
    }

    /**

src/Cenfotec/SeguridadBundle/Resources/views/Usuario/administrar.html.twig
{% extends "::base.html.twig" %}
{% set activePage = 'Seguridad' %}

{# content #}
{% block content %}

    <div id="content">
        <div class="page-header">
            <div class="pull-left">
                <h4><i class="icon-table"></i> Administrar Usuarios</h4>
            </div>
            <div class="pull-right">
                <ul class="bread">
                    <li><a href="#">Seguridad</a><span class="divider">/</span></li>
                    <li class='active'>Usuarios</li>
                </ul>
            </div>
        </div>

        <div class="container-fluid" id="content-area">
            <div class="row-fluid">
                <div class="span12">
                    <div class="crm-box">
                        <div class="crm-box-head">
                            <i class="icon-table"></i>
                            <span>Usuarios</span>
                        </div>
                        <div class="crm-box-body crm-box-body-nopadding">
                            <div id="{{ gridOptionsGenerator.containerId }}"></div>
                            <div class="row-fluid">
                                <div class="span12">
                                    <a href="{{ path('cenfo_usuario_form_registrar') }}" class="button button-basic-green">Agregar nuevo</a>
                                    <a href="{{ path('cenfo_usuario_form_modificar') }}" id="uiBtnModificar" class="button button-basic-blue">Modificar</a>
                                    <a href="{{ path('cenfo_usuario_borrar') }}" class="button button-basic-red">Borrar</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{# javascripts #}
{% block javascripts %}
    {{ parent() }}
    {% include 'ComponentsEJSTreeGridBundle::createGrid.js.twig' with {
        'gridContainerId' : gridOptionsGenerator.containerId, 
        'gridOptions'     : gridOptionsGenerator.options,
        'gridId'          : gridOptionsGenerator.gridId         }
    %}
    <script src="{{ asset('bundles/cenfotecseguridad/js/usuario.js') }}" type="text/javascript"></script>
{% endblock javascripts %}

src/Cenfotec/SeguridadBundle/Resources/views/Usuario/formModificar.html.twig
{% extends "::base.html.twig" %}
{% set activePage = 'Seguridad' %}

{# content #}
{% block content %}

    <div id="content">
        <div class="page-header">
            <div class="pull-left">
                <h4><i class="icon-table"></i> Modificar usuario</h4>
            </div>
            <div class="pull-right">
                <ul class="bread">
                    <li><a href="{{path('cenfo_usuario_administrar')}}">Usuario</a><span class="divider">/</span></li>
                    <li class='active'>Modificar</li>
                </ul>
            </div>
        </div>

        <div class="container-fluid" id="content-area">
            <div class="row-fluid">
                <div class="span12">
                    <div class="crm-box">
                        <div class="crm-box-head">
                            <i class="icon-list-ul"></i>
                            <span>Información del usuario</span>
                        </div>
                        <div class="crm-box-body crm-box-body-nopadding">
                            <form action="{{ path('cenfo_usuario_modificar', { 'pidUsuario' : ptwObjUsuario.id }) }}" id="frmModificarUsuario" method="POST" class="form-horizontal form-bordered form-column form-validate">
                                <div class="span6">
                                    {# Nombre #}
                                    <div class="control-group">
                                        <label for="uiTxtNombre" class="control-label">Nombre <span class="required-label">*</span></label>
                                        <div class="controls">
                                            <input type="text" value="{{ ptwObjUsuario.nombre }}" name="uiDataUsuario[Nombre]" id="uiTxtNombre" placeholder="Ej: Carlos" class="input-block-level" data-rule-required="true">
                                        </div>
                                    </div>
                                    {# Primer apellido #}
                                    <div class="control-group">
                                        <label for="uiTxtApellido1" class="control-label">Primer apellido <span class="required-label">*</span></label>
                                        <div class="controls">
                                            <input type="text" value="{{ ptwObjUsuario.apellido1 }}" name="uiDataUsuario[Apellido1]" id="uiTxtApellido1" placeholder="Ej: Domínguez" class="input-block-level" data-rule-required="true">
                                        </div>
                                    </div>
                                    {# Segundo apellido #}
                                    <div class="control-group">
                                        <label for="uiTxtApellido2" class="control-label">Segundo apellido</label>
                                        <div class="controls">
                                            <input type="text" value="{{ ptwObjUsuario.apellido2 }}" name="uiDataUsuario[Apellido2]" id="uiTxtApellido2" placeholder="Ej: Lara" class="input-block-level">
                                        </div>
                                    </div>
                                    {# Correo electrónico #}
                                    <div class="control-group">
                                        <label for="uiTxtCorreo" class="control-label">Correo electrónico <span class="required-label">*</span></label>
                                        <div class="controls">
                                            <input type="text" value="{{ ptwObjUsuario.correo }}" name="uiDataUsuario[Correo]" id="uiTxtCorreo" placeholder="Ej: krlosnando@gmail.com" class="input-block-level" data-rule-required="true" data-rule-email="true">
                                        </div>
                                    </div>
                                </div>
                                <div class="span6">
                                    {# Nombre de usuario #}
                                    <div class="control-group">
                                        <label for="uiTxtNombreUsuario" class="control-label">Nombre de usuario <span class="required-label">*</span></label>
                                        <div class="controls">
                                            <input type="text" value="{{ ptwObjUsuario.nombreUsuario }}" name="uiDataUsuario[NombreUsuario]" id="uiTxtNombreUsuario" placeholder="Ej: CDominguez" class="input-block-level" data-rule-required="true">
                                        </div>
                                    </div>
                                    {# Seleccionar Roles #}
                                    <div class="control-group">
                                        <label for="uiSelRol" class="control-label">Roles <span class="required-label">*</span></label>
                                        <div class="controls">
                                            <div class="input-block-level">
                                                <select id="uiSelRol" name="uiDataUsuario[Roles][]" data-placeholder="Seleccionar los roles..." multiple=""  data-rule-required="true">
                                                    <option value=""></option>
                                                    {% for objRol in ptwRoles %}
                                                        <option value="{{objRol.id}}" {% if (objRol in ptwObjUsuario.realRoles) %}selected="true"{% endif %}>{{objRol.nombre}}</option>
                                                    {% else %}
                                                        <option value="{{objRol.id}}">{{objRol.nombre}}</option>
                                                    {% endfor %}
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                    {# Contraseña #}
                                    <div class="control-group">
                                        <label for="uiTxtPassword" class="control-label">Contraseña <span class="required-label">*</span></label>
                                        <div class="controls">
                                            <input type="password" value="{{ ptwObjUsuario.password }}" name="uiDataUsuario[Password]" id="uiTxtPassword" class="input-block-level" data-rule-required="true">
                                        </div>
                                    </div>
                                    {# Confirmar Contraseña #}
                                    <div class="control-group">
                                        <label for="uiTxtConfirmarPassword" class="control-label">Confirmar Contraseña <span class="required-label">*</span></label>
                                        <div class="controls">
                                            <input type="password" value="{{ ptwObjUsuario.password }}" name="uiDataUsuario[ConfirmPassword]" id="uiTxtConfirmarPassword" class="input-block-level" data-rule-required="true" data-rule-equalto="#uiTxtPassword">
                                        </div>
                                    </div>
                                </div>
                                <div class="span12">
                                    {# Botones para guardar ó cancelar #}
                                    <div class="form-actions">
                                        <button type="submit" id="uiBtnGuardar" class="button button-basic-green">Guardar</button>
                                        <a href="{{ path('cenfo_usuario_administrar') }}" class="button button-basic-red">Volver</a>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{# javascripts #}
{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('bundles/cenfotecseguridad/js/usuario.js') }}" type="text/javascript"></script>
    <script type="text/javascript">
        
    </script>
{% endblock javascripts %}